### ISSUE TITLE
Elma listesi eklensin ve 10 eleman oluşturulsun ACİL!!!!!!!

### ISSUE THREAD

**Issue by ebarut7** [ebarut7/ConsoleApp2#1]
20 DK VAR PATRON ACİL İSTEDİ ÇABUK.PRİMLERİNİZ KESİLİR.1 tane bug var birde oda düzeltilsin.Patron çıldırdı.

**Comment by DicleSEZER** [comment]
Üzerindeki bug düzeltildi ama hala liste işlemiyle uğraşıyoruz.

**Comment by ebarut7** [comment]
Listenin acil verilmesi gerekiyor

**Comment by DicleSEZER** [comment]
Listeyi gönderdim ya GÖRMEDİNİZ mi ?

**Comment by ebarut7** [comment]
****En yakın zamanda boş evrak imzalatacağım sana :)

**Comment by DicleSEZER** [comment]
İstifa ediyorum...
